apiVersion: apps/v1
kind: Deployment
metadata:
  name: slack-nats
  labels:
    app: slack-nats
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slack-nats
  template:
    metadata:
      labels:
        app: slack-nats
    spec:
      containers:
      - name: slack-nats
        image: natsflow/slack-nats
        env:
        - name: "NATS_URL"
          value: "nats://nats-cluster:4222"
        - name: "SLACK_TOKEN"
          valueFrom:
            secretKeyRef:
              name: slacksecret
              key: slacktoken
