apiVersion: skaffold/v1beta1
kind: Config
build:
  artifacts:
  - image: natsflow/slack-nats
deploy:
  kubectl:
    manifests:
    - deployments/deployment.yaml
profiles:
- name: travis-ci
  build:
    local:
      push: false
- name: travis-release
  build:
    tagPolicy:
      envTemplate:
        template: "{{.IMAGE_NAME}}:{{.TRAVIS_TAG}}"
    local:
      push: false
