apiVersion: skaffold/v1beta1
kind: Config
build:
  artifacts:
  - image: slack-nats
deploy:
  kubectl:
    manifests:
    - deployments/deployment.yaml
profiles:
- name: travis-ci
  build:
    local:
      push: false
